// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKz3kGX94cwHZXNxiDGr67CiQU7gJO5U',
    appId: '1:627643820192:web:7324a51fc835017a4981c5',
    messagingSenderId: '627643820192',
    projectId: 'app141414',
    authDomain: 'app141414.firebaseapp.com',
    storageBucket: 'app141414.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkvoaKRqhBTGVSZlaH3_gdJ52rDCNFCr8',
    appId: '1:627643820192:android:7ca514d56ef1bb9a4981c5',
    messagingSenderId: '627643820192',
    projectId: 'app141414',
    storageBucket: 'app141414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF82qpNafV_GywkCFPAAJmYXBG-n9mezo',
    appId: '1:627643820192:ios:6c175da061a13b494981c5',
    messagingSenderId: '627643820192',
    projectId: 'app141414',
    storageBucket: 'app141414.firebasestorage.app',
    iosBundleId: 'com.example.lab2New',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF82qpNafV_GywkCFPAAJmYXBG-n9mezo',
    appId: '1:627643820192:ios:6c175da061a13b494981c5',
    messagingSenderId: '627643820192',
    projectId: 'app141414',
    storageBucket: 'app141414.firebasestorage.app',
    iosBundleId: 'com.example.lab2New',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKz3kGX94cwHZXNxiDGr67CiQU7gJO5U',
    appId: '1:627643820192:web:1e5d646db3808eab4981c5',
    messagingSenderId: '627643820192',
    projectId: 'app141414',
    authDomain: 'app141414.firebaseapp.com',
    storageBucket: 'app141414.firebasestorage.app',
  );
}
